name: Ruby

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  test:
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', 'jruby', 'truffleruby']
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - ruby-version: truffleruby
            platform: windows-latest
          - ruby-version: jruby
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
